# arxivの学問領域の指定
subject: 'cat:cs.* OR stat.ML'

# 検索キーワード
keywords:
        language: 3
        BERT: 3
        Transformer: 3
        chat: 1
        GAN: 3
        Reinforcement Learning: 2
        Vision and Language: 2

# 通知の閾値
score_threshold: 0
